// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZhuoYue.Components.Code.EntityFrameworkCore;

namespace ZhuoYue.Components.Code.EntityFrameworkCore.SqlServer.Migrations
{
    [DbContext(typeof(CodeDbContext))]
    [Migration("20210106075537_InitialCode")]
    partial class InitialCode
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ZhuoYue.Components.Code.Abstractions.CodeCategory", b =>
                {
                    b.Property<string>("CategoryId")
                        .HasColumnType("nvarchar(36)")
                        .HasMaxLength(36);

                    b.Property<string>("AppId")
                        .HasColumnType("nvarchar(36)")
                        .HasMaxLength(36);

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<DateTime?>("LastUpdatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdatedUserId")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(4096);

                    b.HasKey("CategoryId");

                    b.ToTable("CodeCategories");
                });

            modelBuilder.Entity("ZhuoYue.Components.Code.Abstractions.CodeItem", b =>
                {
                    b.Property<string>("CodeId")
                        .HasColumnType("nvarchar(36)")
                        .HasMaxLength(36);

                    b.Property<string>("CodeCategoryId")
                        .HasColumnType("nvarchar(36)")
                        .HasMaxLength(36);

                    b.Property<string>("CodeName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("CodeValue")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<DateTime?>("LastUpdatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdatedUserId")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(4096);

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.HasKey("CodeId");

                    b.HasIndex("CodeCategoryId");

                    b.ToTable("CodeItems");
                });

            modelBuilder.Entity("ZhuoYue.Components.Code.Abstractions.CodeItem", b =>
                {
                    b.HasOne("ZhuoYue.Components.Code.Abstractions.CodeCategory", "CodeCategory")
                        .WithMany("CodeItems")
                        .HasForeignKey("CodeCategoryId");
                });
#pragma warning restore 612, 618
        }
    }
}
